Symbolic

In [2]:
import sympy as sp
import numpy as np

In [3]:
G11, G12, G21, G22 = sp.symbols('G11, G12, G21, G22')

In [4]:
G = sp.Matrix([[G11, G12], [G21, G22]])
G

Matrix([
[G11, G12],
[G21, G22]])

In [5]:
G.det(), G.inv(), G.T

(G11*G22 - G12*G21,
 Matrix([
 [ G22/(G11*G22 - G12*G21), -G12/(G11*G22 - G12*G21)],
 [-G21/(G11*G22 - G12*G21),  G11/(G11*G22 - G12*G21)]]),
 Matrix([
 [G11, G21],
 [G12, G22]]))

In [6]:
G * G, G + G, G.multiply_elementwise(G)

(Matrix([
 [ G11**2 + G12*G21, G11*G12 + G12*G22],
 [G11*G21 + G21*G22,  G12*G21 + G22**2]]),
 Matrix([
 [2*G11, 2*G12],
 [2*G21, 2*G22]]),
 Matrix([
 [G11**2, G12**2],
 [G21**2, G22**2]]))

numeric

In [10]:
G = np.matrix([[1, 2], [3, 4]])

In [11]:
np.linalg.det(G), G.I, G.T

(-2.0000000000000004,
 matrix([[-2. ,  1. ],
         [ 1.5, -0.5]]),
 matrix([[1, 3],
         [2, 4]]))

In [12]:
G * G, G + G, G.A * G.A

(matrix([[ 7, 10],
         [15, 22]]),
 matrix([[2, 4],
         [6, 8]]),
 array([[ 1,  4],
        [ 9, 16]]))